# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Tim Yanchen Wang'
tagline:          'Digital Maker'
description:      'Personal site for Tim Yanchen Wang'
url:              http://www.timyanchenwang.com
baseurl:          /

author:
  name:           'Tim Yanchen Wang'
  url:            https://twitter.com/besttimyouknow

sass:
  cache: false

gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
  - pygments.rb

paginate: 5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
